version: "3.9"
services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  zookeeper:
    extends:
      file: docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    command: java -jar target/backend.jar

  frontend:
    container_name: frontend
    image: nginx:1.24.0
    volumes:
      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/static/
    ports:
      - "5001:8080"

  text_summarizer:
    extends:
      file: docker-compose.yml
      service: text_summarizer

networks:
  default:
    name: default_network