spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USER:admin}
    password: ${DATASOURCE_PWD:1234}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:9093}
    consumer:
      group-id: text_summarizing
      auto-offset-reset: earliest
      topic: text_summarizing_result
    producer:
      topic: text_summarizing_request

logging:
  level:
    text_summarizing: INFO
    org:
      springframework: INFO

server:
  port: 5000
  servlet:
    session:
      cookie:
        name: TEXT_SUMMARIZE_JSESSIONID

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

max.page.size: 1000